INSERT INTO WAITER (WAITER_ID, WAITER_NAME, WAITER_PHONE_NUMBER, WAITER_DATE_OF_BIRTH) VALUES(21, 'Niyazi KARA', '0501-234-56-79', TO_DATE('12/15/2009', 'MM/DD/YYYY')); 


INSERT INTO WAITER (WAITER_ID, WAITER_NAME, WAITER_PHONE_NUMBER, WAITER_DATE_OF_BIRTH) VALUES(16, 'Fatma Gul', '0503-333-33-32', TO_DATE('04/01/1995', 'MM/DD/YYYY'));
INSERT INTO TABLE_ (TABLE_ID, TABLE_SIZE, TABLE_FLOOR, TABLE_LOCATION, WAITER_ID) VALUES(16, 4, 3, 'inside', 16);
INSERT INTO RESERVATION (RESERVATION_ID, RESERVATION_CUSTOMER_NAME, RESERVATION_TIME, TABLE_ID,RESERVATION_PHONE_NUMBER) VALUES(21,'Ahmet BULUT',TO_TIMESTAMP('01-JAN-2022 22:00', 'DD-MON-YYYY HH24:MI'), 16, '532-234-32-34');
INSERT INTO RESERVATION (RESERVATION_ID, RESERVATION_CUSTOMER_NAME, RESERVATION_TIME, TABLE_ID,RESERVATION_PHONE_NUMBER) VALUES(16,'Salih Bayraktar',TO_TIMESTAMP('01-JAN-2022 22:00', 'DD-MON-YYYY HH24:MI'), 16, '555-888-70-77');
 
INSERT INTO PRODUCT (PRODUCT_COST, PRODUCT_PRICE, PRODUCT_DESCRIPTION, PRODUCT_TYPE)VALUES(25, 30, 'Cream of Mushroom Soup: Brimming with rich, savory flavor, it’s meant to be enjoyed all on its own.', 'soup'); 
INSERT INTO FOOD_INGREDIENT (FOOD_ID, INGREDIENT_ID) VALUES (3, 1); 



INSERT INTO TABLE_ (TABLE_ID, TABLE_SIZE, TABLE_FLOOR, TABLE_LOCATION, WAITER_ID) VALUES(16, 4, 3, 'pool', 16);

INSERT INTO PRODUCT (PRODUCT_COST, PRODUCT_PRICE, PRODUCT_DESCRIPTION, PRODUCT_TYPE)VALUES(-20, 40, 'Shepherd`s pie: Mincemeat topped with mashed potatoes and baked.', 'food');

INSERT INTO PRODUCT (PRODUCT_COST, PRODUCT_PRICE, PRODUCT_DESCRIPTION, PRODUCT_TYPE)VALUES(15, -20, 'Soda: A sweet, carbonated drink.', 'beverage');
